eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    host: localhost
    port: 5672
    username: chams
    password : chams
  kafka:
    bootstrap-servers: localhost:9092
